// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzW6jkQFgvE0vn3SKI65XU6WZGrY8n_6c',
    appId: '1:858928332003:web:743744d32f6eec691fd9d6',
    messagingSenderId: '858928332003',
    projectId: 'iglo-0022',
    authDomain: 'iglo-0022.firebaseapp.com',
    storageBucket: 'iglo-0022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPaO8HtQI1XKJKTe9g3IbJAHRxh56Z17M',
    appId: '1:858928332003:android:34480641e77921d61fd9d6',
    messagingSenderId: '858928332003',
    projectId: 'iglo-0022',
    storageBucket: 'iglo-0022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_6wOCjEm1fIwSIgTFRfsF4KJkbM-qn0',
    appId: '1:858928332003:ios:6e9c2f0bd3032cf61fd9d6',
    messagingSenderId: '858928332003',
    projectId: 'iglo-0022',
    storageBucket: 'iglo-0022.firebasestorage.app',
    iosBundleId: 'com.example.igloo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_6wOCjEm1fIwSIgTFRfsF4KJkbM-qn0',
    appId: '1:858928332003:ios:6e9c2f0bd3032cf61fd9d6',
    messagingSenderId: '858928332003',
    projectId: 'iglo-0022',
    storageBucket: 'iglo-0022.firebasestorage.app',
    iosBundleId: 'com.example.igloo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzW6jkQFgvE0vn3SKI65XU6WZGrY8n_6c',
    appId: '1:858928332003:web:12a41cfb24199c111fd9d6',
    messagingSenderId: '858928332003',
    projectId: 'iglo-0022',
    authDomain: 'iglo-0022.firebaseapp.com',
    storageBucket: 'iglo-0022.firebasestorage.app',
  );
}
